### ISSUE TITLE
0.10 ios版本无法加载出评论区

### ISSUE THREAD

**Issue by sSkieri** [niuhuan/daisy#11]
如题 账号等已登陆
![AF7FFC5C-51A9-4EE2-8A11-CC6AB2D4BFDD](https://user-images.githubusercontent.com/81229545/201966899-eee781bb-0ee0-4eb3-ad22-52139a124032.png)

**Comment by niuhuan** [comment]
我根本搜索不到这本漫画, 其他漫画评论区正常

**Comment by niuhuan** [comment]
稍等我看一下, 我看的是旧版, 好像只有最新版有这个问题

**Comment by sSkieri** [comment]
> 稍等我看一下, 我看的是旧版, 好像只有最新版有这个问题

**Comment by sSkieri** [comment]
好的 明白了 感谢

**Comment by niuhuan** [comment]
已经在构建了, 一会儿下个新版试试

**Comment by sSkieri** [comment]
> 已经在构建了, 一会儿下个新版试试

好的 辛苦了！非常感谢

**Comment by sSkieri** [comment]
可以用了 实测该问题已于0.1.11解决~
