### ISSUE TITLE
无法正常登录，主机中的软件终止了一个已建立的连接 os error 10053

### ISSUE THREAD

**Issue by margin-bqk** [niuhuan/daisy#12]
系统：win10 21h1
应用版本：0.1.11
![image](https://user-images.githubusercontent.com/67771037/202844266-8a9261db-363a-4036-8fdd-a905e4be2a93.png)
账号在官方客户端中可以登录，账号密码也无误。本来想说是不是代理的问题，但是把v2rayN关了也不能解决

**Comment by niuhuan** [comment]
应该不是代理的问题，可能接口迁移了

**Comment by niuhuan** [comment]
已经修复
