### ISSUE TITLE
希望加上通过网址打开漫画功能

### ISSUE THREAD

**Issue by YouGuess11111111** [niuhuan/daisy#15]
大佬你好，dmzj部分漫画搜索时是隐藏的，不知道能不能加个功能能通过网址打开然后放到历史里这样可以从历史打开看，谢谢

**Comment by niuhuan** [comment]
我觉得可以, 或者可以直接从web唤起APP

**Comment by niuhuan** [comment]
v0.1.19 实现了从web点击漫画时直接打开app并且展示漫画详情的功能。
