### ISSUE TITLE
用户数据10G...没有下载过漫画,有什么头猪么

### ISSUE THREAD

**Issue by SlianoShie** [niuhuan/daisy#16]
![Screenshot_20230206-010840](https://user-images.githubusercontent.com/119448704/216833658-7c64e0ca-3f0b-403e-882c-6bf51ec19954.png)
![Screenshot_20230206-010853](https://user-images.githubusercontent.com/119448704/216833666-a11f0235-5228-4ed0-8583-0ad26494c1a6.png)

**Comment by niuhuan** [comment]
有BUG， 稍等修复一下

**Comment by SlianoShie** [comment]
> 有BUG，稻等修复一下

好家伙换了包名,旧APP直接放弃治疗了,希望能出个导入导出历史记录和配置文件的功能,到新APP之后进度都没了

**Comment by niuhuan** [comment]
主要是旧的签名会报毒，我干脆把域名和签名换了

**Comment by niuhuan** [comment]
就算有，emmmm应该也不会用之前的签名了，你可以加一下书签，我应该弄个在线阅读记录的功能

**Comment by SlianoShie** [comment]
> 就算有，emmmm应该也不会用之前的签名了，你可以加一下书签，我应该弄个在线阅读记录的功能

好吧,新包我先用...用一段时间没缓存问题我就关了这个issue了

**Comment by niuhuan** [comment]
新版本如何？

**Comment by SlianoShie** [comment]
> 新版本如何？

问题解决了,基本每天都在看,现在总占用只有241M,是正常的.就是丢了很多阅读进度,每一本漫画我都得重新确认之前看到哪里了,头大.issue解决我关了
![Screenshot_20230314-145231](https://user-images.githubusercontent.com/119448704/224919581-5802ac1f-4ccd-4024-86ea-f2923eb2204d.png)
