### ISSUE TITLE
关于更换为小说模式后的搜索问题

### ISSUE THREAD

**Issue by FespDtion** [niuhuan/daisy#2]
更换为小说模式后 进行搜索后会变成灰屏 没有搜索结果出来 不知原因 很奇怪

**Comment by niuhuan** [comment]
小说的搜索还没有写。预计不同模式下搜不同的资源

**Comment by FespDtion** [comment]
> 小说的搜索还没有写。预计不同模式下搜不同的资源

谢谢解答
