### ISSUE TITLE
flutter_rust_bridge报错，无法运行

### ISSUE THREAD

**Issue by deepindo** [niuhuan/daisy#23]
Because daisy depends on flutter_rust_bridge from path which doesn't exist (could not find package flutter_rust_bridge at "../flutter_rust_bridge/frb_dart"), version solving failed.
pub get failed
command: "/Users/deepindo/Documents/flutter_mac_sdk/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/Users/deepindo/Documents/flutter_mac_sdk/flutter",
  "PUB_ENVIRONMENT": "vscode.dart-code:flutter_cli:get",
  "PUB_CACHE": "/Users/deepindo/.pub-cache",
}
exit code: 66

**Comment by niuhuan** [comment]
您下载releases里的，Gen.zip解压到项目就好了，不需要执行frb如果ios模拟器需要注意一下替换ios-sim里的.a到ios/Runner
