### ISSUE TITLE
0.1.19版本签到失败

### ISSUE THREAD

**Issue by syzomnia-el** [niuhuan/daisy#28]
### 包体

- daisy-v0.1.19-arm64.apk
- of-daisy-v0.1.19-arm64.apk

### 描述

账号正常登录，但签到失败（如下图所示），已排除网络问题。

![错误信息](https://github.com/niuhuan/daisy/assets/54948535/b9c4eef7-709d-4030-a0dd-183c0f54ca70)

**Comment by niuhuan** [comment]
稍等两天再改，快抽散兵专武了
