### ISSUE TITLE
账号

### ISSUE THREAD

**Issue by LovesAsuna** [niuhuan/daisy#3]
账号好像没做？需要同步账号内容。是api没找到吗？

**Comment by niuhuan** [comment]
遇到了点问题，登录的接口api改了，还不知道盐值怎么算的

**Comment by LovesAsuna** [comment]
可能需要逆向官方app？

**Comment by niuhuan** [comment]
> 可能需要逆向官方app？

之前用jadx简单看过他们的代码, 签名都放在的.so里面, 有空需要再逆向看看,。

接口地址
https://user.muwai.com/loginV2/m_confirm

**Comment by niuhuan** [comment]
用vnet抓包，能确定就是md5再转大写，但是还是提示密码错误

**Comment by LovesAsuna** [comment]
不能用网页端来抓包吗？

**Comment by niuhuan** [comment]
用的是APP协议, 跟Cookie不一样, 抓包之后注入token应该能用, 就是很麻烦

**Comment by niuhuan** [comment]
主要是想要那个订阅功能?

**Comment by LovesAsuna** [comment]
对，订阅和历史记录

**Comment by owen800q** [comment]
@niuhuan  我可以幫逆下官方app的簽名算法，有官方apk嗎

**Comment by niuhuan** [comment]
> @niuhuan 我可以幫逆下官方app的簽名算法，有官方apk下載地址嗎

我直接他们从官网下的, 密码md5再转大些, 还需要其他几个参数, 时间戳或者HEADER什么的, 我不知道是不是这个原因。没有总结出规律

**Comment by owen800q** [comment]
@niuhuan 

你那個login api url 錯了?，我試了下是可以 拿到token的

應該是這個，我測試的是用戶名登入, 可能手機號登入有另外一個API, 我沒試手機的


https://nnuser.muwai.com/loginV2/m_confirm

pwd就是md5再转大写
nickname 是用戶名

其他參數_m, _a, _i那幾個都是硬編碼的, 沒有header

CURL sample 如下

`curl --location --request POST 'https://nnuser.muwai.com/loginV2/m_confirm' \
--form 'channel="Android"' \
--form 'timestamp="1651672251"' \
--form 'version="3.7.10"' \
--form '_debug="0"' \
--form 'app_channel="101_01_01_000"' \
--form '_m="D6132DCE99D329CACDE913C7FA952CF3"' \
--form '_a="05CDFDA93076FC56950D6598B94FD986"' \
--form '_i="8508AEE02C57308631D8E5F774D3AABC"' \
--form 'terminal_model="SM-N976N"' \
--form 'nickname="testing"' \
--form 'pwd="DC483E80A7A0BD9EF71D8CF973673924"'`


Response, data 我詳細數據這我就不發出來了

{"result":1,"msg":"登录成功","data":{}}

**Comment by niuhuan** [comment]
似乎是地址的问题，按照别的软件里超过来的就没仔细看

**Comment by suppiac** [comment]
作者你好，我想请问一下请求nnv4api.muwai.com/novel/detail/obj_id的数据应该怎么解析呢？

**Comment by owen800q** [comment]
@suppiac 
解析数据? 他的response body不是明文的嗎，不用特別處理吧

**Comment by suppiac** [comment]
@owen800q 不太清楚刚刚接触，fiddler抓包的时候读取小说详细信息的时候返回值是像加密了的，也有可能是我看错了。

**Comment by suppiac** [comment]
@niuhuan 十分感谢！！！

**Comment by suppiac** [comment]
@owen800q 十分感谢！！！

**Comment by niuhuan** [comment]
@owen800q 

http://${v4}/comic/detail 接口使用的参数coreToken是.so算的。如果不知道怎么算,就没有办法知道这个动漫有没有被订阅。

**Comment by owen800q** [comment]
@niuhuan  我这边看到的是coreToken是明文， 没有看到类似sign的参数

![Capture](https://user-images.githubusercontent.com/19252045/167116798-ff65e438-01f4-4409-9921-81f95d72c93f.PNG)

**Comment by niuhuan** [comment]
> @niuhuan 我这边看到的是coreToken是明文， 没有看到类似sign的参数

这个token是根据时间戳算出来的, 每次请求都不一样, 想拿到这个

**Comment by niuhuan** [comment]
如果弄不了，就只能做个本地书签和订阅了。后期再做个和官方账号的同步功能，

**Comment by owen800q** [comment]
@niuhuan 

coreToken 已經分析出咗了，我用python 寫了sample, 你可以測試下

https://gist.github.com/owen800q/342229586ddec777f42ea21bd16e8806

**Comment by owen800q** [comment]
@niuhuan 
右手邊那個地方, 對應python sample 的 

right_part_core_token = [md5_hash[i:i+2] for i in range(0, len(md5_hash), 2)]

只是把md5後的結果 58d0ec998ab114830ff8d3d3194b2599 

轉成這個格式

58:D0:EC:99:8A:B1:14:83:0F:F8:D3:D3:19:4B:25:99

**Comment by owen800q** [comment]
@niuhuan 另外想問下，接口相關的代碼不在這個repository 嗎?  我沒找到rust 相關的部份

**Comment by niuhuan** [comment]
> @niuhuan 另外想問下，接口相關的代碼不在這個repository 嗎? 我沒找到rust 相關的部份

没有在里面，native部分在私有仓库，之前看到有的jinman客户端被直接编译然后去收费的情况，我就把所有作品native和gui分开管理了。

**Comment by niuhuan** [comment]
> @niuhuan 右手邊那個地方, 對應python sample 的
> 
> right_part_core_token = [md5_hash[i:i+2] for i in range(0, len(md5_hash), 2)]
> 
> 只是把md5後的結果 58d0ec998ab114830ff8d3d3194b2599
> 
> 轉成這個格式
> 
> 58:D0:EC:99:8A:B1:14:83:0F:F8:D3:D3:19:4B:25:99

时间戳的md5吗？我试一下。

**Comment by owen800q** [comment]
> > @niuhuan 右手邊那個地方, 對應python sample 的
> > right_part_core_token = [md5_hash[i:i+2] for i in range(0, len(md5_hash), 2)]
> > 只是把md5後的結果 58d0ec998ab114830ff8d3d3194b2599
> > 轉成這個格式
> > 58:D0:EC:99:8A:B1:14:83:0F:F8:D3:D3:19:4B:25:99
> 
> 时间戳的md5吗？我试一下。

不只是時間戳

hash_body = 'com.dmzj.manhua63:60:C8:3B:75:31:3F:35:EC:41:1D:85:60:63:EB:25{timestamp}+bYV5TaOBivUHM'.format(timestamp=timestamp)

其他參數都是硬編碼的，替換下時間戳就好

**Comment by niuhuan** [comment]
@owen800q  把你加到[daisy-rs-core](https://github.com/niuhuan/daisy-rs-core)的成员里了。

你如果感兴趣可以看一下。

运行起来十分麻烦
先克隆 flutter_rust_bridge, daisy, 在同一目录下, 再克隆 daisy-rs-core 到daisy目录下并叫 native。
然后按照githubActions里面编译的步骤才可以。

**Comment by niuhuan** [comment]
账号登录的功能在继续开发。

**Comment by niuhuan** [comment]
@owen800q  你是怎么找到.so里面的内容的？

**Comment by owen800q** [comment]
@niuhuan 汇编调试的
