### ISSUE TITLE
daisy和of-daisy有什么区别 

### ISSUE THREAD

**Issue by ts8zs** [niuhuan/daisy#31]
[daisy-v0.1.21-arm64.apk](https://github.com/niuhuan/daisy/releases/download/v0.1.21/daisy-v0.1.21-arm64.apk)
[of-daisy-v0.1.21-arm64.apk](https://github.com/niuhuan/daisy/releases/download/v0.1.21/of-daisy-v0.1.21-arm64.apk)
readme好像没讲这两个是有什么区别? of是?

**Comment by niuhuan** [comment]
old flutter 老的机器可以用 但是bug多
