### ISSUE TITLE
漫画分区不全

### ISSUE THREAD

**Issue by onlytheworld** [niuhuan/daisy#6]
您好，dmzj的漫画从分类这一栏只能看到部分分类，但实际点进任一分类内部后，点击题材就可以看到全部的分类了，希望可以补上，谢谢！
![Screenshot_20220511_095623_com dmzj manhua](https://user-images.githubusercontent.com/37205103/167753469-0e62a97e-a7a2-4e03-9017-3c44669ffb17.jpg)

**Comment by niuhuan** [comment]
1

**Comment by niuhuan** [comment]
已经加上了, 重新下一下最后一版本的release。
