### ISSUE TITLE
阅读器类型: 相册

### ISSUE THREAD

**Issue by JohnnyLee0215** [niuhuan/daisy#7]
阅读器类型为相册时，不论翻页类型为何，图片只会以填充而不是适应的形式展现在屏幕上，一定程度上影响了正常阅读。

**Comment by niuhuan** [comment]
已经修复并push代码,  正在构建
https://github.com/niuhuan/daisy/actions/runs/2308826195

等待他完成并下载最新release就可以了

**Comment by JohnnyLee0215** [comment]
感谢，晚安
