### ISSUE TITLE
019版ios只有内地漫画

### ISSUE THREAD

**Issue by pingshu** [niuhuan/daisy#9]
其他地区空白
![3F68F099-8EF9-49B8-B869-C9DDAB6FC413](https://user-images.githubusercontent.com/22138807/197471741-2edf2bc3-ce30-4372-b8c3-9aec0e0af58b.png)

**Comment by niuhuan** [comment]
估计大妈之家又搞什么事情了, 这两天有空抓包, debug一下。

**Comment by niuhuan** [comment]
已更新
